# Generated by Django 3.1.6 on 2021-02-12 22:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(default='', max_length=5, unique=True)),
                ('short_name', models.CharField(default='', max_length=25)),
                ('long_name', models.CharField(default='', max_length=256)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('invested', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('stocks_bought', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=60, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('funds', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stocks', models.ManyToManyField(to='Portfolio.Stock')),
            ],
        ),
    ]
